name: Deploy to Azure

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  APP_NAME: "Asteroid"
  PACKAGE_PATH: "."
  NODE_VERSION: "20.x"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Build app
        run: npm run build --if-present

      - name: Test app
        run: npm run test --if-present

      - name: Update artifacts
        uses: actions/upload-artifacts@v4.6.2
        with:
          name: asteroid-app
          path: ./build
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: asteroid-app

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.6
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.ASTEROID_PUBLISH_PROFILE }}
          package: ${{ env.PACKAGE_PATH }}
